version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
  app:
    container_name: spring-library
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres?currentSchema=library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_FLYWAY_ENABLED: False
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=1 -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - app
volumes:
  db-data:
