version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=1 -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  app:
    container_name: spring-library
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db-data:
