server:
 port: 8080

spring:
 application:
   name: spring-library
 datasource:
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: false
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    temp.use_jdbc_metadata_defaults: false
  show-sql: true
 data:
  rest:
   base-path: /datarest

management:
 endpoints:
  web:
   exposure:
    include: health,metrics,logfile,hystrix.stream
 endpoint:
  health:
   show-details: always
  metrics:
   enabled: true
  logfile:
   enabled: true
 health:
  defaults:
   enabled: true

logging:
 level:
  root: INFO
 file:
  name: ./logs/spring-boot-logger.log
