spring:
 datasource:
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library
  username: postgres
  password: 1
  driverClassName: org.postgresql.Driver

 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: false
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    temp.use_jdbc_metadata_defaults: false
  show-sql: true
logging:
 level:
  root: ERROR
server:
 port: 8080
